site_name: 经天纬地的笔记
copyright: Copyright &copy; 2021 - 2023 Zouwei 
site_description: 经天纬地的笔记本
repo_name: WaynePancho/note
repo_url: https://github.com/WaynePancho/WaynePancho.github.io

extra:
  generator: false

theme:
  name: material
  language: 'zh'
  icon: 
    logo: material/notebook-outline
    custom_dir: overrides
    features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.path
  font: false
  palette:
      # Palette toggle for automatic mode
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode

      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default 
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.tabbed:
  #     alternate_style: true 
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  # - pymdownx.highlight:
  #     anchor_linenums: true


extra_javascript:
  # - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - js/katex.js
  # - js/heti.js
  # - js/scheme.js # this is in template 'base.html'

extra_css:
  # - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  # - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  # - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - css/tasklist.css
  - css/custom.css
  - css/card.css
  - css/flink.css
  - css/changelog_extra.css
  # - css/heti.css




nav:
  - 主页: 
    - index.md
    - 更新记录: changelog.md
  - 物理: 
    - physics/index.md
    - 经典力学:
      - physics/经典力学/index.md
      - 从最小作用量原理导出牛顿第一和第二定律: physics/经典力学/一、从最小作用量原理导出牛顿第一和第二定律.md
  - 数学:
    - math/index.md 
    - 微积分:
      - math/微积分/index.md
      - 泰勒展开的几种形式: math/微积分/泰勒展开的几种形式.md
  - 计科: 
    - computer/index.md