site_name: 经天纬地的笔记本
copyright: Copyright &copy; 2021 - 2023 Zouwei Pan
site_description: 经天纬地的笔记本
repo_name: WaynePancho/note
repo_url: https://github.com/WaynePancho/note

# extra:
#   generator: false

theme:
  name: material
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.path
  font: false
  palette:
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default 
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to system preference
      # Palette toggle for automatic mode
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode
  features:
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - tables
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true


extra_javascript:
  # - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - js/katex.js
  # - js/heti.js
  # - js/scheme.js # this is in template 'base.html'

extra_css:
  # - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  # - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  # - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - css/tasklist.css
  - css/custom.css
  # - css/card.css
  - css/flink.css
  - css/changelog_extra.css
  # - css/heti.css

plugins:
    - changelog


nav:
  - 主页: 
    - index.md
    - 更新记录: changelog.md
  - 物理:
    - physics/index.md
    - 经典力学:
      - physics/classical_mechanics/index.md
      - 从最小作用量原理导出牛顿第一和第二定律: physics/classical_mechanics/1.md
    - 计算物理:
      - physics/computational_physics/index.md
      - 微分方程数值解:
        - physics/computational_physics/DE/index.md
        - 冷却问题: 
          - physics/computational_physics/DE/cooling/index.md
          - 欧拉算法: physics/computational_physics/DE/cooling/1.md
          - 作业题: physics/computational_physics/DE/cooling/lab.md
    - 粒子物理:
      - physics/particle_physics/index.md
      - 标准模型中的粒子: physics/particle_physics/1.md
    - 散射振幅:
      - physics/scattering_amplitude/index.md
      - 符号约定: physics/scattering_amplitude/1.md
      - Yukawa理论的树级振幅: physics/scattering_amplitude/2.md
  - 数学:
    - math/index.md 
    - 微积分:
      - math/calculus/index.md
      - 泰勒展开的几种形式: math/calculus/1.md
  - 计科: 
    - computer/index.md